config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    get "/posts/:id/comments", to: "comments#index", as: :comments
    post "/posts/:id/like", to: "posts#like", as: :like
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :manage, User, id: user.id
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  belongs_to :post

  after_save :update_post_comments_counter

  def as_json(_options = {})
    super(only: %i[id text author_id created_at updated_at])
  end

  private

  def update_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  belongs_to :post

  after_save :update_post_likes_counter

  private

  def update_post_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
  after_save :update_user_posts_counter

  def as_json(_options = {})
    super(only: %i[id title text author_id created_at updated_at comments_counter likes_counter])
  end

  private

  def update_user_posts_counter
    user.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    if request.format == :json
      render json: Comment.all
    else
      render plain: '404 Not Found'
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(author_id: current_user.id, post_id: @post.id, text: params[:comment])
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      render :show, alert: 'Error occured!'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!

  def show
    render json: { message: "If you see this, you're in!" }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 2)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user.posts }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @user = current_user
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @post = Post.new(post_params)
    @user = current_user
    if @post.save
      puts 'Post created successfully'
      redirect_to user_posts_path(current_user)
    else
      render :new, alert: 'Error occured!'
    end
  end

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end

  def like
    @post = Post.find(params[:id])
    Like.new(author_id: current_user.id, post_id: @post.id).save
    redirect_to user_post_path(current_user)
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @post.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json

  private

  def respond_with(_resource, _opts = {})
    register_success && return if resource.persisted?

    register_failed
  end

  def register_success
    render json: { message: 'Signed up sucessfully.' }
  end

  def register_failed
    render json: { message: 'Something went wrong.' }
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(_resource, _opts = {})
    render json: { message: 'You are logged in.' }, status: :ok
  end

  def respond_to_on_destroy
    log_out_success && return if current_user

    log_out_failure
  end

  def log_out_success
    render json: { message: 'You are logged out.' }, status: :ok
  end

  def log_out_failure
    render json: { message: 'Hmm nothing happened.' }, status: :unauthorized
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def authenticate_user!
    redirect_to '/users/sign_in' unless current_user
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MvBlogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= current_user.name %>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%=link_to @user do %>
  <div class="user">
    <div class="userPhoto blackMargin"><%=image_tag @user.photo %></div>
    <div class="name blackMargin">
      <h3><%= @user.name %></h3>
      <small>Number of posts: <%= @user.posts_counter %></small>
    </div>
  </div>
<% end %>
<% unless @posts.nil? %>
  <ul class="postsL">
    <% @posts.each do |post| %>
      <div class="post blackMargin">
        <small>Post #<%= post.id %></small>
        <h3><%=link_to post.title, user_post_path(@user, post) %></h3>
        <p><%= post.text %></p>
        <small class="counters">Comments: <%= post. comments_counter %>, Likes: <%= post.likes_counter %></  small>
        <% if can? :destroy, post %>
          <%= button_to 'Delete', user_post_path(post.author_id, post.id), method: :delete %>
        <% end %>
        </small>
      </div>
      
      <div class="blackMargin">
        <% post.recent_comments.includes([:user]).each do |comment| %>
          <%= comment.user.name %>: <%= comment.text %></br>
        <% end %>
      </div>
    <% end %>
  </ul>
<% end %>
<div class="seeAllBtn blackMargin"><%=link_to "New Post", new_user_post_path(@user), class: 'show-posts'%></div>
<div class="center"><%= will_paginate @posts %></div>

app/views/posts/new.html.erb
<div class="form">
  <%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |f| %>
    <%= f.hidden_field :author_id, value: @user.id %>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'fileBox' %><br>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'fileBox' %><br>
    <%= f.submit "Post", class: 'btn' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post blackMargin">
  <small>Post #<%= @post.id %> by <%= @post.user.name %></small>
  <small class="counters">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></small>
  <h3><%= @post.title %></h3>
  <p><%= @post.text %></p>
</div>
<div class="blackMargin">
  <% @comments.each do |comment| %>
    <p>
      <%= comment.user.name %>: <%= comment.text %>
      <% if can? :destroy, comment %>
        <%= button_to 'Delete', user_post_comment_path(current_user.id, @post.id, comment.id), method: :delete, class: 'del' %>
      <% end %>
    <p>
  <% end %>
</div>

<%= form_with url: user_like_path(@user, @post), method: :post do |f| %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit "Like", class: 'btn' %>
<% end %>

<%= form_with :url => user_post_comments_path(@user, @post), method: :post do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :author_id, value: @user.id %>
  <%= f.text_area :comment, placeholder: 'Comment', class: 'fileBox' %><br>
  <%= f.submit "Comment", class: 'btn' %>
<% end %>

app/views/users/index.html.erb
<ul class="usersL">
  <% @users.each do |user| %>
    <div class="user">
      <div class="userPhoto blackMargin"><%=image_tag user.photo %></div>
      <div class="name blackMargin">
        <h3><%=link_to user.name, user %></h3>
        <small>Number of posts: <%= user.posts_counter %></small>
      </div>
    </div>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="user">
  <div class="userPhoto blackMargin"><%=image_tag @user.photo %></div>
  <div class="name blackMargin">
    <h3><%= @user.name %></h3>
    <small>Number of posts: <%= @user.posts_counter %></small>
  </div>
</div>
<div class="bio blackMargin">
  <h3>Bio</h3>
  <p><%= @user.bio %></p>
</div>
<ul class="postsL">
  <% @user.recent_posts.each do |post| %>
    <div class="post blackMargin">
      <h3><%=link_to post.title, user_post_path(@user, post) %></h3>
      <p><%= post.text %></p>
      <small>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></small>
      <small class="counters">
        <% if can? :destroy, post %>
          <%= button_to 'Delete', user_post_path(@user.id, post.id), method: :delete %>
        <% end %>
      </small>
    </div>
  <% end %>
  <div class='botBtn'>
    <div class="seeAllBtn blackMargin"><%=link_to "See All Posts", user_posts_path(@user), class: 'show-posts'%></div>
    <div class="seeAllBtn blackMargin"><%=link_to "New Post", new_user_post_path(@user), class: 'show-posts'%></div>
  </div>
</ul>